### ISSUE TITLE
CMake errors with build directories that contain spaces (or other special characters)

### ISSUE THREAD

**Issue by raymondlanger** [LLNL/sundials#46]
In `config/SundialsFortran.cmake`, please change lines 217 and 270 from

~~~~~~~~~~~
"FIND_LIBRARY(FLIB flib ${FortranTest_DIR})\n"
~~~~~~~~~~~

to

~~~~~~~~~~~
"FIND_LIBRARY(FLIB flib \"${FortranTest_DIR}\")\n"
~~~~~~~~~~~

This change avoids CMake errors if the build directory contains special characters like spaces.

**Comment by balos1** [comment]
Should be fixed in v5.5.0. Reopen the issue if it persists.

**Comment by raymondlanger** [comment]
The double quotes are still missing in `cmake/SundialsSetupFortran.cmake` in line 260 in the current version of sundials (5.7.0).

**Comment by balos1** [comment]
Fixed in v5.8.0.
